### ISSUE TITLE
音形码不对啊

### ISSUE THREAD

**Issue by seantdj** [wenyangchou/SimilarCharactor#1]
音形码第三位表示补码，如果不存在应该用0表示

**Comment by wenyangchou** [comment]
这个音形码是自定义的，应该跟你理解的音形码不是一个

**Comment by seantdj** [comment]
ok，我看了csdn上的那个文章，音形码由10位组成，我看你文件中有8位和9位


来自 魅族 16th

-------- 原始邮件 --------
发件人：zhouwenyang <notifications@github.com>
时间：2019年7月16日 19:24
收件人：wenyangchou/SimilarCharactor <SimilarCharactor@noreply.github.com>
抄送：seantdj <seantdj@sina.com>,Author <author@noreply.github.com>
主题：Re: [wenyangchou/SimilarCharactor] 音形码不对啊 (#1)
